name: Build Content

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  build-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Build Parser
        working-directory: ./parser
        run: cargo build --release --all-features
      
      - run: ls -al
