name: Build Content

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  build-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - uses: actions/cache@v3
        with:
          path: | 
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./parser/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build Parser
        if: steps.cache-numbers.outputs.cache-hit != 'true'
        working-directory: ./parser
        run: cargo build --release --all-features
      
      - name: Compile Data
        run: |
          mv ./parser/target/release/parser ./data/
          cd data/
          ./parser -i ./ -o ./compiled
          cd ../
          mv ./data/compiled/ ./compiled
      
      - name: List All
        run: ls -al ./compiled
      
