name: Build Content

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  build-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Build Parser
        if: steps.cache-numbers.outputs.cache-hit != 'true'
        run: npm install && npm start -- -i "data/**/*.md" -o "./compiled"

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: guides-compiled
          SKIP_EMPTY_COMMITS: true
          FOLDER: compiled
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
